### ISSUE TITLE
Online party

### ISSUE THREAD

**Issue by zakblacki** [opsilonn/mobileDev_WerewolfCompanionApp#1]
C'est bien dommage j'adore l'interface mais on peut pas jouer en ligne

**Comment by opsilonn** [comment]
Merci beaucoup Zak :)
Pour ce qui est de jouer en ligne : j'ai juste conçu cette appli pour qu'elle aide le MJ en présentiel (exit les cartes ou livrets de règle, un smartphone suffit), je ne l'ai pas pensé pour des parties à distance... Donc je pense que dans ce cas, d'autres applications répondent mieux à cette problématique.
